[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.4"
  GO_VERSION = "1.22.2"
  HUGO_ENABLEGITINFO = "true"

[dev]
  command = "hugo server --disableFastRender"
  framework = "hugo"
  targetPort = 1313

[deploy]
  command = "netlify deploy --prod --dir=public"

#[[redirects]]
#  from = "https://andremoreno.netlify.app/*"
#  to = "https://www.andremoreno.id/:splat"
#  status = 301
#  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"