[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
  GO_VERSION = "1.22.3"
  HUGO_ENABLEGITINFO = "true"

[dev]
  command = "hugo server --disableFastRender"
  framework = "hugo"
  targetPort = 1313

[deploy]
  command = "netlify deploy --prod --dir=public"

#[[redirects]]
#  from = "https://andremoreno.netlify.app/*"
#  to = "https://www.andremoreno.id/:splat"
#  status = 301
#  force = true


[[redirects]]
  # Serve a full size version
  from = "/static/*"
  to = "/.netlify/images?url=/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404




[[headers]]
  for = "/fonts/*"
    [headers.values]
     "Cache-Control" = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/scss/*"
    [headers.values]
     "Cache-Control" = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/js/*"
    [headers.values]
     "Cache-Control" = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/images/*"
    [headers.values]
     "Cache-Control" = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"


[[headers]]
  for = "/static/*"
    [headers.values]
     "Cache-Control" = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"